// Generated by gencpp from file cloud_robot/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_ADDTWOINTS_H
#define CLOUD_ROBOT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <cloud_robot/AddTwoIntsRequest.h>
#include <cloud_robot/AddTwoIntsResponse.h>


namespace cloud_robot
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace cloud_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cloud_robot::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::cloud_robot::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::cloud_robot::AddTwoInts > {
  static const char* value()
  {
    return "cloud_robot/AddTwoInts";
  }

  static const char* value(const ::cloud_robot::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::cloud_robot::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::cloud_robot::AddTwoInts > 
template<>
struct MD5Sum< ::cloud_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::AddTwoInts >::value();
  }
  static const char* value(const ::cloud_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::AddTwoIntsRequest> should match 
// service_traits::DataType< ::cloud_robot::AddTwoInts > 
template<>
struct DataType< ::cloud_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::AddTwoInts >::value();
  }
  static const char* value(const ::cloud_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cloud_robot::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::cloud_robot::AddTwoInts > 
template<>
struct MD5Sum< ::cloud_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::AddTwoInts >::value();
  }
  static const char* value(const ::cloud_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::AddTwoIntsResponse> should match 
// service_traits::DataType< ::cloud_robot::AddTwoInts > 
template<>
struct DataType< ::cloud_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::AddTwoInts >::value();
  }
  static const char* value(const ::cloud_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_ADDTWOINTS_H
