// Generated by gencpp from file cloud_robot/SortingInts.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_SORTINGINTS_H
#define CLOUD_ROBOT_MESSAGE_SORTINGINTS_H

#include <ros/service_traits.h>


#include <cloud_robot/SortingIntsRequest.h>
#include <cloud_robot/SortingIntsResponse.h>


namespace cloud_robot
{

struct SortingInts
{

typedef SortingIntsRequest Request;
typedef SortingIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SortingInts
} // namespace cloud_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cloud_robot::SortingInts > {
  static const char* value()
  {
    return "ff865f8228965906870e73f7c2b0295b";
  }

  static const char* value(const ::cloud_robot::SortingInts&) { return value(); }
};

template<>
struct DataType< ::cloud_robot::SortingInts > {
  static const char* value()
  {
    return "cloud_robot/SortingInts";
  }

  static const char* value(const ::cloud_robot::SortingInts&) { return value(); }
};


// service_traits::MD5Sum< ::cloud_robot::SortingIntsRequest> should match 
// service_traits::MD5Sum< ::cloud_robot::SortingInts > 
template<>
struct MD5Sum< ::cloud_robot::SortingIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::SortingInts >::value();
  }
  static const char* value(const ::cloud_robot::SortingIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::SortingIntsRequest> should match 
// service_traits::DataType< ::cloud_robot::SortingInts > 
template<>
struct DataType< ::cloud_robot::SortingIntsRequest>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::SortingInts >::value();
  }
  static const char* value(const ::cloud_robot::SortingIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cloud_robot::SortingIntsResponse> should match 
// service_traits::MD5Sum< ::cloud_robot::SortingInts > 
template<>
struct MD5Sum< ::cloud_robot::SortingIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::SortingInts >::value();
  }
  static const char* value(const ::cloud_robot::SortingIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::SortingIntsResponse> should match 
// service_traits::DataType< ::cloud_robot::SortingInts > 
template<>
struct DataType< ::cloud_robot::SortingIntsResponse>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::SortingInts >::value();
  }
  static const char* value(const ::cloud_robot::SortingIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_SORTINGINTS_H
