// Generated by gencpp from file cloud_robot/SortingIntsResponse.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_SORTINGINTSRESPONSE_H
#define CLOUD_ROBOT_MESSAGE_SORTINGINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_robot
{
template <class ContainerAllocator>
struct SortingIntsResponse_
{
  typedef SortingIntsResponse_<ContainerAllocator> Type;

  SortingIntsResponse_()
    : sorted()  {
    }
  SortingIntsResponse_(const ContainerAllocator& _alloc)
    : sorted(_alloc)  {
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _sorted_type;
  _sorted_type sorted;




  typedef boost::shared_ptr< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SortingIntsResponse_

typedef ::cloud_robot::SortingIntsResponse_<std::allocator<void> > SortingIntsResponse;

typedef boost::shared_ptr< ::cloud_robot::SortingIntsResponse > SortingIntsResponsePtr;
typedef boost::shared_ptr< ::cloud_robot::SortingIntsResponse const> SortingIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_robot::SortingIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cloud_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'cloud_robot': ['/home/abner0908/catkin_ws/src/cloud_robot/msg', '/home/abner0908/catkin_ws/devel/share/cloud_robot/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92a09364fc58f1a7dbbfb4f90451ded1";
  }

  static const char* value(const ::cloud_robot::SortingIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92a09364fc58f1a7ULL;
  static const uint64_t static_value2 = 0xdbbfb4f90451ded1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_robot/SortingIntsResponse";
  }

  static const char* value(const ::cloud_robot::SortingIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] sorted\n\
\n\
";
  }

  static const char* value(const ::cloud_robot::SortingIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sorted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SortingIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_robot::SortingIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_robot::SortingIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sorted[]" << std::endl;
    for (size_t i = 0; i < v.sorted.size(); ++i)
    {
      s << indent << "  sorted[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.sorted[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_SORTINGINTSRESPONSE_H
