// Generated by gencpp from file cloud_robot/TimerActionGoal.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_TIMERACTIONGOAL_H
#define CLOUD_ROBOT_MESSAGE_TIMERACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <cloud_robot/TimerGoal.h>

namespace cloud_robot
{
template <class ContainerAllocator>
struct TimerActionGoal_
{
  typedef TimerActionGoal_<ContainerAllocator> Type;

  TimerActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  TimerActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::cloud_robot::TimerGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::cloud_robot::TimerActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_robot::TimerActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TimerActionGoal_

typedef ::cloud_robot::TimerActionGoal_<std::allocator<void> > TimerActionGoal;

typedef boost::shared_ptr< ::cloud_robot::TimerActionGoal > TimerActionGoalPtr;
typedef boost::shared_ptr< ::cloud_robot::TimerActionGoal const> TimerActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_robot::TimerActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cloud_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'cloud_robot': ['/home/abner0908/catkin_ws/src/cloud_robot/msg', '/home/abner0908/catkin_ws/devel/share/cloud_robot/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::TimerActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::TimerActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::TimerActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db74ec180ecb81d0542047d87021844f";
  }

  static const char* value(const ::cloud_robot::TimerActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb74ec180ecb81d0ULL;
  static const uint64_t static_value2 = 0x542047d87021844fULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_robot/TimerActionGoal";
  }

  static const char* value(const ::cloud_robot::TimerActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
TimerGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: cloud_robot/TimerGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# This is an action definition file, which has three parts: the goal, the\n\
# result, and the feedback.\n\
#\n\
# Part 1: the goal, to be sent by the client\n\
#\n\
# The amount of time we want to wait\n\
duration time_to_wait\n\
";
  }

  static const char* value(const ::cloud_robot::TimerActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TimerActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_robot::TimerActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_robot::TimerActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::cloud_robot::TimerGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_TIMERACTIONGOAL_H
