// Generated by gencpp from file cloud_robot/WordCountTypeResponse.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPERESPONSE_H
#define CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_robot
{
template <class ContainerAllocator>
struct WordCountTypeResponse_
{
  typedef WordCountTypeResponse_<ContainerAllocator> Type;

  WordCountTypeResponse_()
    : count(0)  {
    }
  WordCountTypeResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
    }



   typedef uint32_t _count_type;
  _count_type count;




  typedef boost::shared_ptr< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WordCountTypeResponse_

typedef ::cloud_robot::WordCountTypeResponse_<std::allocator<void> > WordCountTypeResponse;

typedef boost::shared_ptr< ::cloud_robot::WordCountTypeResponse > WordCountTypeResponsePtr;
typedef boost::shared_ptr< ::cloud_robot::WordCountTypeResponse const> WordCountTypeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cloud_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cloud_robot': ['/home/abner0908/catkin_ws/src/cloud_robot/msg', '/home/abner0908/catkin_ws/devel/share/cloud_robot/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac8b22eb02c1f433e0a55ee9aac59a18";
  }

  static const char* value(const ::cloud_robot::WordCountTypeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac8b22eb02c1f433ULL;
  static const uint64_t static_value2 = 0xe0a55ee9aac59a18ULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_robot/WordCountTypeResponse";
  }

  static const char* value(const ::cloud_robot::WordCountTypeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 count\n\
\n\
";
  }

  static const char* value(const ::cloud_robot::WordCountTypeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WordCountTypeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_robot::WordCountTypeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_robot::WordCountTypeResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPERESPONSE_H
