// Generated by gencpp from file cloud_robot/WordCountType.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPE_H
#define CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPE_H

#include <ros/service_traits.h>


#include <cloud_robot/WordCountTypeRequest.h>
#include <cloud_robot/WordCountTypeResponse.h>


namespace cloud_robot
{

struct WordCountType
{

typedef WordCountTypeRequest Request;
typedef WordCountTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCountType
} // namespace cloud_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cloud_robot::WordCountType > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::cloud_robot::WordCountType&) { return value(); }
};

template<>
struct DataType< ::cloud_robot::WordCountType > {
  static const char* value()
  {
    return "cloud_robot/WordCountType";
  }

  static const char* value(const ::cloud_robot::WordCountType&) { return value(); }
};


// service_traits::MD5Sum< ::cloud_robot::WordCountTypeRequest> should match 
// service_traits::MD5Sum< ::cloud_robot::WordCountType > 
template<>
struct MD5Sum< ::cloud_robot::WordCountTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::WordCountType >::value();
  }
  static const char* value(const ::cloud_robot::WordCountTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::WordCountTypeRequest> should match 
// service_traits::DataType< ::cloud_robot::WordCountType > 
template<>
struct DataType< ::cloud_robot::WordCountTypeRequest>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::WordCountType >::value();
  }
  static const char* value(const ::cloud_robot::WordCountTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cloud_robot::WordCountTypeResponse> should match 
// service_traits::MD5Sum< ::cloud_robot::WordCountType > 
template<>
struct MD5Sum< ::cloud_robot::WordCountTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cloud_robot::WordCountType >::value();
  }
  static const char* value(const ::cloud_robot::WordCountTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cloud_robot::WordCountTypeResponse> should match 
// service_traits::DataType< ::cloud_robot::WordCountType > 
template<>
struct DataType< ::cloud_robot::WordCountTypeResponse>
{
  static const char* value()
  {
    return DataType< ::cloud_robot::WordCountType >::value();
  }
  static const char* value(const ::cloud_robot::WordCountTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPE_H
