// Generated by gencpp from file cloud_robot/WordCountTypeRequest.msg
// DO NOT EDIT!


#ifndef CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPEREQUEST_H
#define CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cloud_robot
{
template <class ContainerAllocator>
struct WordCountTypeRequest_
{
  typedef WordCountTypeRequest_<ContainerAllocator> Type;

  WordCountTypeRequest_()
    : words()  {
    }
  WordCountTypeRequest_(const ContainerAllocator& _alloc)
    : words(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _words_type;
  _words_type words;




  typedef boost::shared_ptr< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WordCountTypeRequest_

typedef ::cloud_robot::WordCountTypeRequest_<std::allocator<void> > WordCountTypeRequest;

typedef boost::shared_ptr< ::cloud_robot::WordCountTypeRequest > WordCountTypeRequestPtr;
typedef boost::shared_ptr< ::cloud_robot::WordCountTypeRequest const> WordCountTypeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cloud_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'cloud_robot': ['/home/abner0908/catkin_ws/src/cloud_robot/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f897d3845272d18053a750c1cfb862a";
  }

  static const char* value(const ::cloud_robot::WordCountTypeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f897d3845272d18ULL;
  static const uint64_t static_value2 = 0x053a750c1cfb862aULL;
};

template<class ContainerAllocator>
struct DataType< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cloud_robot/WordCountTypeRequest";
  }

  static const char* value(const ::cloud_robot::WordCountTypeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string words\n\
";
  }

  static const char* value(const ::cloud_robot::WordCountTypeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WordCountTypeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cloud_robot::WordCountTypeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cloud_robot::WordCountTypeRequest_<ContainerAllocator>& v)
  {
    s << indent << "words: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.words);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOUD_ROBOT_MESSAGE_WORDCOUNTTYPEREQUEST_H
