(cl:defpackage cloud_robot-srv
  (:use )
  (:export
   "WORDCOUNTTYPE"
   "<WORDCOUNTTYPE-REQUEST>"
   "WORDCOUNTTYPE-REQUEST"
   "<WORDCOUNTTYPE-RESPONSE>"
   "WORDCOUNTTYPE-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SORTINGINTS"
   "<SORTINGINTS-REQUEST>"
   "SORTINGINTS-REQUEST"
   "<SORTINGINTS-RESPONSE>"
   "SORTINGINTS-RESPONSE"
  ))

